package main

import (
	"fmt"
	"log"
	"os"

	"github.com/davidpalaitis/golars"
)

func main() {
	// Example 1: Create and write a DataFrame to CSV
	fmt.Println("=== Example 1: Writing DataFrame to CSV ===")
	
	// Create a sample DataFrame
	df, err := golars.NewDataFrame(
		golars.NewStringSeries("name", []string{"Alice", "Bob", "Charlie", "David"}),
		golars.NewInt64Series("age", []int64{25, 30, 35, 40}),
		golars.NewFloat64Series("score", []float64{95.5, 87.0, 92.3, 88.7}),
		golars.NewBooleanSeries("active", []bool{true, false, true, true}),
	)
	if err != nil {
		log.Fatal(err)
	}
	
	// Write to CSV file
	err = golars.WriteCSV(df, "output.csv")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Written DataFrame to output.csv")
	
	// Example 2: Read CSV file
	fmt.Println("\n=== Example 2: Reading CSV file ===")
	
	// Read the CSV file we just wrote
	df2, err := golars.ReadCSV("output.csv")
	if err != nil {
		log.Fatal(err)
	}
	
	fmt.Printf("Read DataFrame with %d rows and %d columns\n", df2.Height(), df2.Width())
	fmt.Printf("Columns: %v\n", df2.Columns())
	
	// Print first few rows
	fmt.Println("\nFirst 3 rows:")
	for i := 0; i < 3 && i < df2.Height(); i++ {
		for _, col := range df2.Columns() {
			s, _ := df2.Column(col)
			fmt.Printf("%s: %v\t", col, s.Get(i))
		}
		fmt.Println()
	}
	
	// Example 3: Write with custom options
	fmt.Println("\n=== Example 3: Writing with custom options ===")
	
	// Create DataFrame with nulls
	dfWithNulls, err := golars.NewDataFrame(
		golars.NewStringSeries("product", []string{"Laptop", "Mouse", "Keyboard"}),
		golars.NewSeriesWithValidity("price", []float64{999.99, 19.99, 0}, []bool{true, true, false}, golars.Float64),
		golars.NewSeriesWithValidity("stock", []int64{10, 0, 25}, []bool{true, false, true}, golars.Int64),
	)
	if err != nil {
		log.Fatal(err)
	}
	
	// Write with custom options
	err = golars.WriteCSV(dfWithNulls, "products.csv",
		golars.WithWriteDelimiter(';'),
		golars.WithNullValue("N/A"),
		golars.WithFloatFormat("%.2f"),
	)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Written DataFrame with custom options to products.csv")
	
	// Show the file content
	content, _ := os.ReadFile("products.csv")
	fmt.Println("File content:")
	fmt.Println(string(content))
	
	// Example 4: Read with custom options
	fmt.Println("\n=== Example 4: Reading with custom options ===")
	
	// Read the semicolon-delimited file
	df3, err := golars.ReadCSV("products.csv",
		golars.WithDelimiter(';'),
		golars.WithNullValues([]string{"N/A"}),
	)
	if err != nil {
		log.Fatal(err)
	}
	
	fmt.Println("Successfully read semicolon-delimited CSV")
	
	// Check null values
	priceCol, _ := df3.Column("price")
	stockCol, _ := df3.Column("stock")
	
	fmt.Printf("Price column null at index 2: %v\n", priceCol.IsNull(2))
	fmt.Printf("Stock column null at index 1: %v\n", stockCol.IsNull(1))
	
	// Example 5: Read specific columns
	fmt.Println("\n=== Example 5: Reading specific columns ===")
	
	// Read only name and score columns from the first file
	df4, err := golars.ReadCSV("output.csv",
		golars.WithColumns([]string{"name", "score"}),
	)
	if err != nil {
		log.Fatal(err)
	}
	
	fmt.Printf("Read only selected columns: %v\n", df4.Columns())
	
	// Example 6: Skip rows and comments
	fmt.Println("\n=== Example 6: Handling comments and skip rows ===")
	
	// Create a CSV with comments
	csvWithComments := `# This is a data file
# Generated by our system
id,value,category
1,100,A
2,200,B
# Mid-file comment
3,300,C
4,400,D`
	
	err = os.WriteFile("commented.csv", []byte(csvWithComments), 0644)
	if err != nil {
		log.Fatal(err)
	}
	
	// Read with comment handling
	df5, err := golars.ReadCSV("commented.csv",
		golars.WithComment('#'),
		golars.WithSkipRows(2), // Skip the first two comment lines
	)
	if err != nil {
		log.Fatal(err)
	}
	
	fmt.Printf("Read CSV with comments, got %d rows\n", df5.Height())
	
	// Clean up example files
	os.Remove("output.csv")
	os.Remove("products.csv")
	os.Remove("commented.csv")
	
	fmt.Println("\n=== Example complete ===")
}